### ISSUE TITLE
save figures in plotSpikeDetectionChecks

### ISSUE THREAD

**Issue by yuanyin98** [SAND-Lab/MEA-NAP#17]
**Links for variables in debug mode:** https://www.dropbox.com/s/p3usfpxivmjls56/matlabWorkspace_%20plotSpikeDetectionChecks20220815.mat?dl=0
https://www.dropbox.com/s/s48fkqw02c531t3/matlabWorkspace_%20pipelineSaveFig20220815.mat?dl=0

**Output folder link:** 
https://www.dropbox.com/sh/csiowbzwewkdv2o/AABaRzlKBCDbuqN3OGDNCszQa?dl=0

**Actual error message:**
Error using save
Error closing file C:\Users\Sand Box\Dropbox (Cambridge University)\Sand Box PC
MATLAB\MATLAB\MEAGit202208\OutputData15Aug2022\1_SpikeDetection\1B_SpikeDetectionChecks\PostStim\220725_Mutant_ALICO1_6_poststim\ExampleTraces.fig.
The file may be corrupt.

Error in matlab.graphics.internal.figfile.FigFile/write (line 32)
save(obj.Path, obj.MatVersion, '-struct', 'SaveVars');

Error in savefig (line 83)
FF.write();

Error in saveasfig (line 6)
savefig(h, name);

Error in saveas (line 153)
    feval( ['saveas' format], h, name )

Error in pipelineSaveFig (line 54)
            saveas(gcf, figFileName);

Error in plotSpikeDetectionChecks (line 216)
pipelineSaveFig(figName, Params.figExt, Params.fullSVG)

**Comment by yuanyin98** [comment]
Links for variables: https://www.dropbox.com/s/p3usfpxivmjls56/matlabWorkspace_%20plotSpikeDetectionChecks20220815.mat?dl=0
https://www.dropbox.com/s/s48fkqw02c531t3/matlabWorkspace_%20pipelineSaveFig20220815.mat?dl=0

**Comment by yuanyin98** [comment]
Output folder link: https://www.dropbox.com/sh/csiowbzwewkdv2o/AABaRzlKBCDbuqN3OGDNCszQa?dl=0

**Comment by Timothysit** [comment]
Closing this issue because Params.oneFigure is no longer used in the latest version (v1.4.0) of the pipeline. The pipeline now uses the variable `OneFigureHandle` to handle this.
