### ISSUE TITLE
Error in Step1 Spike Detection: unable to remove grounded electrodes

### ISSUE THREAD

**Issue by yuanyin98** [SAND-Lab/MEA-NAP#19]
**Troubleshooted and found**
Params.electrodesToGroundPerRecording shows NaN

**Links to variables**
https://www.dropbox.com/s/pkuochqi5vpu5c5/matlabWorkspace_GroundingElectrodes_Mutant_ALICO6_20220815.mat?dl=0

**Actual error message:**
Index exceeds the number of array elements (1).

Error in batchDetectSpikes (line 165)
            groundElectrodeStr = params.('electrodesToGroundPerRecording'){recording};

Error in MEApipelineMeCP2ALICO20220810 (line 204)
        batchDetectSpikes(rawData, savePath, option, ExpName, Params);

**Comment by Timothysit** [comment]
Hi Yin, can you also upload the csv file you used here? Seems to be do with matlab reading the csv in a weird way

**Comment by yuanyin98** [comment]
Hi Tim! Here it is: https://www.dropbox.com/s/6knzuk0gv5klv03/MeCP2_20220725_Mutant_ALICO6.csv?dl=0

**Comment by Timothysit** [comment]
Hi Yin, I just added a line to ask matlab to interpret the 4th column of the spreadsheet to be `char`, which should do it, let me know if it works.

Change is in commit: https://github.com/SAND-Lab/AnalysisPipeline/commit/51773af7a8680b0736090686815dcff0087d2479
