### ISSUE TITLE
Licence file needed

### ISSUE THREAD

**Issue by sje30** [SAND-Lab/MEA-NAP#36]
Hi all,

the repository needs a LICENCE file so that users know what they can do with the code.

Some suggestions:

MIT - very relaxed

GPL - if others release the code, they must also release it under GPL 

e.g. see: https://www.codecademy.com/article/choosing-an-open-source-license

**Comment by Timothysit** [comment]
Thanks! I have added a GPL-3.0 Licence in the commit here: 39ca298
