### ISSUE TITLE
Error in raw data folder input

### ISSUE THREAD

**Issue by adampavlinek** [SAND-Lab/MEA-NAP#40]
I get the following error when inputing the raw data folder using the GUI:

Unrecognized method, property, or field 'RawDataFolderEditField_2' for class
'MEANAPApp'.

Error in runPipelineApp (line 123)
        app.RawDataFolderEditField_2.Value = app.RawDataFolderEditField.Value;

Error in MEApipeline (line 78)
    runPipelineApp

**Comment by Timothysit** [comment]
Hi, sorry this is likely due to a work in progress feature in the GUI, I have committed a new version of the GUI code just now, can you download it and try again? Let me know if this fixes it / the issue persists. Thanks!

**Comment by adampavlinek** [comment]
Hi thanks that solved it!
