### ISSUE TITLE
High Pass Filter Not Working for Axion Maestro MEA Data

### ISSUE THREAD

**Issue by davidioluigbo** [SAND-Lab/MEA-NAP#49]
After I updated to the most recent version, the GUI seems to not be working with my Axion Maestsro MEA data. I collected this data at 12500 Hz with a down sampling factor of 12500 Hz. 

Here is a screenshot of the error:
<img width="947" alt="Screenshot 2024-03-25 at 1 31 47 PM" src="https://github.com/SAND-Lab/MEA-NAP/assets/95871175/155e56bf-156f-49f2-9a96-92704ca927b6">

**Comment by Timothysit** [comment]
Should be fixed in this commit: 1fed13af7889b948b463f4e0c3afbfee141145d6
