### ISSUE TITLE
File conversion issue

### ISSUE THREAD

**Issue by adampavlinek** [SAND-Lab/MEA-NAP#50]
Hi
I started running a new set of RAW files through file conversion and I'm getting the following error:

Unrecognized function or variable 'fFilename'.

Error in CombinedBlockVectorHeaderEntry.Deserialize (line 208)
                error('BlockVectorMetaData checksum was incorrect: %s', fFilename);

Error in AxisFile (line 326)
                            fCombinedBlockVector = CombinedBlockVectorHeaderEntry.Deserialize(entryRecord, this.FileID);

Error in rawConvertFunc (line 94)
            AllData = AxisFile(fullfile(raw_file_dir, filenames(i).name)).RawVoltageData.LoadData;

Error in runPipelineApp (line 265)
            rawConvertFunc(app.MEANAPFolderEditField.Value, app.DataFolderEditField.Value, ...

Error in MEApipeline (line 79)
    runPipelineApp

**Comment by Timothysit** [comment]
Hi, what kind of (Axion) file .raw are you trying to convert? How are they different from the previous ones you've tried?

**Comment by adampavlinek** [comment]
Hi the length is the same and the plate layout is the same, it’s just a different recording and file name as far as I’m aware

**Comment by adampavlinek** [comment]
I tried changing the file names to exactly match the previous recordings, but I am still getting the same error.

**Comment by Timothysit** [comment]
Hi sorry for the delay, would you mind emailing me the problematic file so I can try to read it to see if it is problem with the code / perhaps file corruption? Have you tried reading the file using other software?

**Comment by adampavlinek** [comment]
Hi, it seems to be a problem across all the files I've tested. No issues opening them in other software. Will try and find a way of sharing a sample file with you. Thanks!

**Comment by Timothysit** [comment]
Hi, this seem to be caused by an old version of Axion File Loader, I have added the latest version now and it worked for the file you sent me, please test it out and let me know how it goes!

**Comment by adampavlinek** [comment]
Hi thanks that fixed it!
