### ISSUE TITLE
Error before 2B 

### ISSUE THREAD

**Issue by kamaood** [SAND-Lab/MEA-NAP#55]
Hi I keep running into an error before step 2B:

Error using PlotEphysStats
Invalid expression. When calling a function or indexing a variable, use
parentheses. Otherwise, check for mismatched delimiters.

Error in MEApipeline (line 333)
    PlotEphysStats(ExpName,Params,HomeDir, oneFigureHandle)

I was just wondering if it could be because I am trying to compare 4 different treatment conditions  - is this possible? 

Thanks!

**Comment by Timothysit** [comment]
Hi, thanks for using the pipeline! The pipeline should be able to handle 4 groups, can I ask what are you group names / whether there are any special characters in your group names (such as `#?()*`), as those may cause issues. Another possibility is that the `PlotEphysStats.m` file has been modified for some reason, in which case you should replace it with version on github. Let me know how it goes!

**Comment by kamaood** [comment]
Hi, I had the concentration of treatments in the names! Have now changed it but now I get this error instead: 

Error using PlotEphysStats
Incorrect use of '=' operator. Assign a value to a variable using '=' and
compare values for equality using '=='.

I haven't modified the file at all !

**Comment by Timothysit** [comment]
Hi, can you let me know what the group names are? Perhaps they have an equal sign (`=`) in them? Sorry I forgot to mention that you also don't want special characters such as the equal sign in the names.

**Comment by kamaood** [comment]
Hi,

Yep, they are Vehicle, 5MeODMT, Psilocin and DOI. 5MeODMT was previously separated with a dash (-) but I've now removed it! Now I am getting this error:

Error using PlotEphysStats
Invalid expression. Check for missing multiplication operator, missing or
unbalanced delimiters, or other syntax error. To construct matrices, use
brackets instead of parentheses.

**Comment by Timothysit** [comment]
Try removing the dot `.` after DOI? Also note group names cannot begin with numbers, so `5MeODMT` also needs to be changed. Sorry for the inconvenience! It is on my todos to add more flexibility to the group names.

**Comment by kamaood** [comment]
Great thank you!
